version: "3.7"

services:
  back:
    build:
      context: .
      dockerfile: hseling_api_judgment/Dockerfile
    volumes:
      - ./sudact_database/sudact.sqlite:/app/sudact.sqlite
    ports:
      - 5000:80
  front:
    build:
      context: .
      dockerfile: hseling_web_judgment/Dockerfile
    ports:
      - 8000:80
